name: Build and Push Omnivore Docker Images

on:
  push:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Get metadata for Docker images
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          isfire/omnivore-api
          isfire/omnivore-web
          isfire/omnivore-fetch
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: |
          ./packages/api/Dockerfile
          ./packages/web/Dockerfile
          ./packages/content-fetch/Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        build-args: |
          APP_ENV=prod
          BASE_URL=http://localhost:3000
          SERVER_BASE_URL=http://localhost:4000
          HIGHLIGHTS_BASE_URL=http://localhost:3000
        platforms: linux/amd64,linux/arm64
